CREATE OR REPLACE VIEW public.posthog_completed_analysis_view AS
SELECT
    pva.id as analysis_id,
    pva.posthog_id_uuid,
    psd.session_id,
    psd.user_id,
    psd.frontegg_id,
    psd.client_id,
    psd.tenant_id,
    psd.assignment_id,
    psd.pl_group_id,
    psd.schedule_id,
    psd.activity_type,
    psd.experience_type,
    prr.start_time,
    prr.end_time,
    prr.recording_duration,
    prr.active_seconds,
    prr.inactive_seconds,
    prr.click_count,
    prr.keypress_count,
    prr.mouse_activity_count,
    psd.public_url,
    pva.langfuse_trace_url,
    (pva.llm_analysis->'phase_analysis'->'authentication'->>'is_smooth')::boolean as auth_phase_smooth,
    pva.llm_analysis->'phase_analysis'->'authentication'->'issues' as auth_phase_issues,
    (pva.llm_analysis->'phase_analysis'->'call_selection'->>'is_smooth')::boolean as selection_phase_smooth,
    pva.llm_analysis->'phase_analysis'->'call_selection'->'issues' as selection_phase_issues,
    (pva.llm_analysis->'phase_analysis'->'call_initiation'->>'is_smooth')::boolean as initiation_phase_smooth,
    pva.llm_analysis->'phase_analysis'->'call_initiation'->'issues' as initiation_phase_issues,
    (pva.llm_analysis->'phase_analysis'->'report_review'->>'is_smooth')::boolean as report_review_phase_smooth,
    pva.llm_analysis->'phase_analysis'->'report_review'->'issues' as report_review_phase_issues,
    (pva.llm_analysis->'overall_analysis'->>'total_duration_seconds')::integer as total_duration_seconds,
    (pva.llm_analysis->'overall_analysis'->>'excess_time_seconds')::integer as excess_time_seconds,
    (pva.llm_analysis->'overall_analysis'->>'exceeds_target')::boolean as exceeds_target,
    pva.llm_analysis->'overall_analysis'->'user 